name: Playwright Tests
on:
  push:
    Branches: [ main ]
jobs:
  playwrighttest:
    runs-on: ubuntu-latest
    steps: 
      -  name: Checkout repository
         uses: actions/checkout@v2
      -  name: Say hello
         run: echo Hello